[project]
name = "westgate"
version = "0.1.1"
description = "My small project"
dependencies = [
    'pandas >= 2.2.1' 
]

[build-system]
requires=["setuptools ~= 69.0.3"]

[tool.setuptools.packages.find]
include = ["westgate*"]